default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: seq_assignment_dev

test:
  <<: *default
  database: seq_assignment_test

production:
  <<: *default
  database: seq_assignment_prod
